const fs=require('fs'),path=require('path');
const root=__dirname;
const movies=[['aliens','Aliens','f8ecd26f06f378b9c3a9.jpg','GXpS2dlpN8Y'],['matrix','The Matrix','da18af071b136cb10721.jpg','yelcMpN_qXw'],['gladiator','Gladiator','63edd8b11ee134050f7e.jpg','mUip4g7ScWQ'],['the-fifth-element','The Fifth Element','0c12892366ac52e29518.jpg','Wre64C_kcik'],['starship-troopers','Starship Troopers','f925a131f342513262da.jpg','zPYuV_jGk7M']];
const titles={home:'Home','services-7':'Services','about-us':'About Us',contact:'Contact','payment-request-page':'Payment enquiries',...Object.fromEntries(movies.map(m=>[m[0],m[1]]))};
const dataPath=path.join(root,'site-content.json');
// Preserve the original rich text before replacing Wix-generated HTML.
if(!fs.existsSync(dataPath)){
 const content={};
 for(const slug of Object.keys(titles)){
  const source=fs.readFileSync(path.join(root,'pages',slug+'.html'),'utf8');
  content[slug]=[...source.matchAll(/<div[^>]+class="[^"]*wixui-rich-text[^>]*>([\s\S]*?)<\/div>/g)].map(m=>m[1])
    .filter(s=>! /TrueFocus5D Newsletter|See it First|©|&copy;|Back to Catalogue|Contact Us now for|Pre-Order Now|Let us know your interested/.test(s))
    .map(s=>s.replace(/\s(?:style|class|id|data-[\w-]+)="[^"]*"/g,'').replace(/<\/?span[^>]*>/g,'').replace(/<a\b[^>]*>([\s\S]*?)<\/a>/g,'$1').replace(/<h[1-6]\b[^>]*>/g,'<h2>').replace(/<\/h[1-6]>/g,'</h2>').replace(/<p>\s*(?:&nbsp;|\u200b|<br\s*\/?>|\s)*<\/p>/g,''));
 }
 fs.writeFileSync(dataPath,JSON.stringify(content,null,2));
}
const content=JSON.parse(fs.readFileSync(dataPath));
const escape=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
function page(slug,prefix){
 const link=s=>prefix+(s==='home'?'index.html':s+'.html');
 const asset=f=>prefix+'assets/'+f;
 const navLink=(s,label)=>`<a href="${link(s)}"${slug===s?' aria-current="page"':''}>${label}</a>`;
 const gallery=()=>`<div class="film-grid">${movies.map(([s,t,img])=>`<a class="film" href="${link(s)}"><img src="${asset(img)}" alt="${t} poster" width="400" height="600" loading="lazy"><span>${t}<small>Watch the 3D preview ↗</small></span></a>`).join('')}</div>`;
 let main='';
 if(slug==='home') main=`<section class="hero"><img class="hero-backdrop" src="${asset('1f287e15e1217b953557.jpg')}" alt="" fetchpriority="high"><div class="hero-content"><p class="eyebrow">2D to 3D conversion · Creative development</p><h1>TrueFocus<br>5D Studios</h1><p class="lead">Specializing in 2D to 3D conversion.</p><p>Stable depth. Smooth motion. Immersive experiences. Transform video and film into stereoscopic 3D, multi-view 3D, and AR / VR ready content.</p><div class="actions"><a class="button" href="${link('services-7')}">Explore our 3D services</a><a class="button secondary" href="#conversions">Watch previews ↓</a></div></div></section><section class="section" id="conversions"><p class="eyebrow">See the difference</p><h2>Our latest 3D conversions</h2>${gallery()}</section><section class="section split"><div><p class="eyebrow">Built for depth</p><h2>From your screen.<br>Into your world.</h2><p>TrueFocus 5D Studios is dedicated to transforming 2D content into immersive 3D VR experiences. Our AI-driven conversion pipeline focuses on quality, realism, and stability over long sequences.</p><p>The TrueFocus Real-Time 3D Player renders novel views from source video and depth in real time. Supports SD, HD, UHD, 4K, 8K and 16K input video.</p><a class="text-link" href="${link('about-us')}">About the studio →</a></div><video controls playsinline preload="none" poster="${asset('9ce21cef8cb41bc5b12a.jpg')}" aria-label="TrueFocus conversion demonstration"><source src="${asset('4b6279f2df7da9ad4f24.mp4')}" type="video/mp4"><a href="${asset('4b6279f2df7da9ad4f24.mp4')}">Download the demonstration video</a></video></section>`;
 else if(movies.some(m=>m[0]===slug)){
  const [,title,img,youtube]=movies.find(m=>m[0]===slug);
  main=`<section class="section"><a class="text-link" href="${link('home')}#conversions">← All conversions</a><p class="eyebrow">TrueFocus 3D conversion</p><h1>${title}</h1><div class="video-frame"><iframe src="https://www.youtube-nocookie.com/embed/${youtube}" title="${title} conversion preview" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><p><a class="text-link" href="https://www.youtube.com/watch?v=${youtube}" target="_blank" rel="noopener noreferrer">Watch on YouTube ↗</a></p><div class="prose">${content[slug].join('\n')}</div><a class="button" href="${link('contact')}">Ask about this conversion</a></section><section class="section"><h2>Explore more conversions</h2>${gallery()}</section>`;
 }else if(slug==='contact') main=`<section class="section contact"><p class="eyebrow">Let’s create depth</p><h1>Contact TrueFocus<br>5D Studios</h1><p class="lead">Have footage you’d like to see in 3D?</p><p>Tell us about your project, its duration, source resolution, and the output format you have in mind.</p><a class="button email" href="mailto:contact_us@truefocus5dstudios.com">contact_us@truefocus5dstudios.com ↗</a><p>TrueFocus5DStudios LLC<br>Washington, DC, USA</p></section>`;
 else if(slug==='payment-request-page') main=`<section class="section prose"><h1>Payment enquiries</h1><p>Contact the studio for your project quote and payment instructions.</p><a class="button" href="mailto:contact_us@truefocus5dstudios.com?subject=Project%20payment%20enquiry">Contact the studio</a></section>`;
 else main=`<section class="section"><p class="eyebrow">TrueFocus 5D Studios</p><h1>${titles[slug]}</h1><div class="prose">${content[slug].join('\n')}</div><a class="button" href="${link('contact')}">Discuss your project →</a></section>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="TrueFocus 5D Studios — AI-driven 2D to 3D video conversion and immersive AR / VR experiences."><meta name="color-scheme" content="dark"><title>${escape(titles[slug])} | TrueFocus 5D Studios</title><link rel="icon" href="${asset('03320a27c705d944336a.webp')}"><link rel="stylesheet" href="${prefix}site.css"><script src="${prefix}site.js" defer></script></head><body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="nav-shell"><a class="brand" href="${link('home')}" aria-label="TrueFocus 5D Studios home"><img src="${asset('03320a27c705d944336a.webp')}" alt="" width="70" height="36"><span>TRUEFOCUS<small>5D STUDIOS</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav">Menu <span aria-hidden="true">☰</span></button><nav id="primary-nav" aria-label="Main navigation">${navLink('home','Home')}${navLink('services-7','Services')}<details class="conversions"><summary${movies.some(m=>m[0]===slug)?' class="active"':''}>3D Conversions <span aria-hidden="true">⌄</span></summary><div class="dropdown">${movies.map(m=>navLink(m[0],m[1])).join('')}</div></details>${navLink('about-us','About Us')}${navLink('contact','Contact')}</nav></div></header><main id="main" tabindex="-1">${main}</main><footer><div class="footer-inner"><div><strong>TRUEFOCUS 5D STUDIOS</strong><p>2D to 3D. A new dimension of storytelling.</p></div><a href="mailto:contact_us@truefocus5dstudios.com">Contact the studio ↗</a><small>© ${new Date().getFullYear()} TrueFocus5DStudios.</small></div></footer></body></html>`;
}
for(const slug of Object.keys(titles)){
 const primary=slug==='home'?'index.html':slug+'.html';fs.writeFileSync(path.join(root,primary),page(slug,''));
 for(const dir of ['pages','local-pages'])fs.writeFileSync(path.join(root,dir,slug+'.html'),page(slug,'../'));
}
console.log('Built 10 responsive pages and 20 compatible saved-page routes.');
