const fs=require('fs'),path=require('path'),crypto=require('crypto'),{execFile}=require('child_process');
const root=__dirname,m=JSON.parse(fs.readFileSync(path.join(root,'manifest.json')));
function get(item){return new Promise(resolve=>execFile('curl.exe',['--globoff','-L','--fail','--silent','--show-error','--connect-timeout','15','--max-time','60',item.url,'-o',path.join(root,item.file)],(e,out,err)=>{item.ok=!e;if(e)item.error=err.slice(0,400);else {delete item.error;item.bytes=fs.statSync(path.join(root,item.file)).size;}resolve();}));}
async function batch(items){let i=0;await Promise.all(Array.from({length:5},async()=>{while(i<items.length)await get(items[i++]);}));}
(async()=>{
await batch(m.assets.filter(a=>!a.ok));
const deps=new Map();
for(const a of m.assets.filter(a=>a.ok&&a.file.endsWith('.css'))){const css=fs.readFileSync(path.join(root,a.file),'utf8');for(const match of css.matchAll(/url\(\s*['"]?([^)'"\s]+)['"]?\s*\)/g)){try{const url=new URL(match[1],a.url).href;if(url.startsWith('https:')&&!m.assets.some(x=>x.url===url)){const ext=path.extname(new URL(url).pathname)||'.bin';deps.set(url,{url,file:'assets/'+crypto.createHash('sha256').update(url).digest('hex').slice(0,20)+ext});}}catch{}}}
const recovered=[...deps.values()].filter(a=>fs.existsSync(path.join(root,a.file))); for(const a of recovered){a.ok=true;a.bytes=fs.statSync(path.join(root,a.file)).size;} m.assets.push(...recovered); m.unfetchedStylesheetDependencies=[...deps.values()].filter(a=>!fs.existsSync(path.join(root,a.file))).map(a=>a.url);
fs.mkdirSync(path.join(root,'local-pages'),{recursive:true});
const replacements=[...m.assets.filter(a=>a.ok),...m.pages.filter(p=>p.ok).map(p=>({...p,file:'local-pages/'+path.basename(p.file)}))].sort((a,b)=>b.url.length-a.url.length);
for(const p of m.pages.filter(p=>p.ok)){let html=fs.readFileSync(path.join(root,p.file),'utf8');for(const a of replacements){html=html.split(a.url).join('../'+a.file);html=html.split(a.url.replace(/&/g,'&amp;')).join('../'+a.file);}fs.writeFileSync(path.join(root,'local-pages',path.basename(p.file)),html);}
fs.writeFileSync(path.join(root,'manifest.json'),JSON.stringify(m,null,2));
const ok=m.assets.filter(a=>a.ok),bad=m.assets.filter(a=>!a.ok),videos=ok.filter(a=>a.file.endsWith('.mp4'));
const summary={pages:m.pages.filter(p=>p.ok).length,assets:ok.length,videoFiles:videos.length,failed:bad.length,assetBytes:ok.reduce((n,a)=>n+a.bytes,0)};
fs.writeFileSync(path.join(root,'BACKUP-NOTES.txt'),`TRUEFOCUS WEBSITE RECOVERY BACKUP\nSource: ${m.source}\nSaved: ${m.createdAt}\n${JSON.stringify(summary,null,2)}\n\npages/: unmodified HTML snapshots of all 9 linked public pages.\nlocal-pages/: copies with directly referenced saved URLs rewritten locally; Wix dynamic scripts can still require online services.\nassets/: images, original-resolution images, 2 background videos in 4 resolutions each, styles, scripts, fonts and CSS dependencies.\ntext/: readable text extracted from each page.\nmanifest.json: exact source URLs, local paths, byte counts and failures.\ndns-backup.zone: previously saved DNS records.\n\nLIMITATIONS\nThis is a recovery archive, not a standalone operational Wix site. Wix forms, newsletter, login, chat and dynamic video library/backend data must be recreated or exported separately. Embedded YouTube videos are preserved as URLs, not downloaded video files. No authentication or paywall was bypassed. Failed assets are listed in manifest.json.\n`);
fs.writeFileSync(path.join(root,'index.html'),'<!doctype html><meta charset="utf-8"><title>TrueFocus backup</title><style>body{font:18px system-ui;max-width:900px;margin:40px auto;line-height:1.6}a{color:#1260a0}</style><h1>TrueFocus website backup</h1><p>'+summary.pages+' pages; '+summary.assets+' assets; '+(summary.assetBytes/1048576).toFixed(1)+' MiB of assets.</p><p>This archive preserves the site for rebuilding. Wix services and embedded YouTube video files are not included.</p><ul>'+m.pages.filter(p=>p.ok).map(p=>'<li>'+(p.url.slice(m.source.length)||'Home')+' — <a href="'+p.file+'">Original HTML</a> | <a href="local-pages/'+path.basename(p.file)+'">Local assets version</a> | <a href="text/'+path.basename(p.file,'.html')+'.txt">Text</a></li>').join('')+'</ul><p><a href="BACKUP-NOTES.txt">Backup notes</a> | <a href="manifest.json">File inventory</a></p>');
console.log(JSON.stringify(summary));console.log('Remaining unavailable assets:',JSON.stringify(bad.map(a=>({url:a.url,error:a.error}))));
})();
